### ISSUE TITLE
subsecond accuracy

### ISSUE THREAD

**Issue by Bennofue** [dleutnant/influxdbr#31]
Für die Datenanalyse wird in manchen Fällen der genau Zeitstempel inkl. der Millisekunden benötigt.
Standardmäßig wird aktuell ja nur folgendes Format von einer Abfrage zurückgeliefert: "yyyy-MM-dd hh:mm:ss". Gibt es eine Möglichkeit das Format um die MS zu erweitern?

**Comment by dleutnant** [comment]
Yes, `influxdbr` supports milliseconds accuracy. If you write data to InfluxDB set the precision parameter to `ms`. 
But maybe your indices returned have already subsecond accuracy. In order to make it visible set `options(digits.secs = 3)` which controls the maximum number of digits to print.  

Let me know if this works for you
